include:
  local: .gitlab.base-ci.yml
stages:
  - build
  - sonarqube-check

sonarqube-check:
  stage: sonarqube-check
  when: always
  needs:
    - build
  allow_failure: false
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: gradle test jacocoTestReport sonarqube --stacktrace
  only:
    - main
    - merge_requests
