stages:
  - sonarqube

include:
  template: base-gitlab-cy.yml

sonarqube-check:
  stage: sonarqube
  when: always
  needs: [ test ]
  allow_failure: false
  cache:
    key: "${CI_JOB_NAME}"
    paths: .sonar/cache
  script:
    - gradle jacocoTestReport
    - sonarqube --stacktrace
  only:
    - main
    - merge_requests