version: '2'
services:
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - /data/db

  starwars-api:
    depends_on:
      - mongo-db
    links:
      - mongo-db
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-db/starwars
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: starwars-api