spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      username:
      database: starwars
      password:
      authSource: admin

cloud:
  aws:
    sqs:
      endpoint: defaultEndPoint