server:
  port: 8080
  servlet:
    context-path: /api/v0/
  error:
    path: /resource-error

clients:
  starwars:
    name: starwars
    url: https://swapi.dev/api/

feign:
  client:
    config:
      starwars:
        connectTimeout: 1000
        readTimeout: 10000

spring:
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      username: ${DB_USERNAME}
      database: ${DB_NAME}
      password: ${DB_PASSWORD}
      authSource: ${DB_AUTH_SOURCE}

aws:
  sqs:
    access:
      key: ${SQS_ACCESS_KEY}
    secret:
      key: ${SQS_SECRET_KEY}
    planet:
      delete:
        url: ${SQS_PLANET_DELETE_URL}